import React, {useMemo, useState} from 'react';
import {Search, Menu, UserRound, ChevronDown, ArrowUpRight, Headphones, Laptop, Smartphone, Cpu, Watch, Gamepad2, SlidersHorizontal, Heart, Star, Zap, ShieldCheck, Truck, X} from 'lucide-react';

const categories=[
 {name:'Mobiles',icon:Smartphone,sub:'Phones for every budget'},
 {name:'Laptops',icon:Laptop,sub:'Work, study & gaming'},
 {name:'Audio',icon:Headphones,sub:'Hear every detail'},
 {name:'PC Components',icon:Cpu,sub:'Build your setup'},
 {name:'Accessories',icon:Watch,sub:'Small things, big upgrades'},
 {name:'Gaming',icon:Gamepad2,sub:'Level up your play'}
];
const products=[
 {id:1,name:'Nothing Phone (2a)',brand:'Nothing',category:'Mobiles',price:23999,old:27999,rating:4.5,tag:'Best value',image:'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=85',spec:'8GB RAM · 128GB · AMOLED'},
 {id:2,name:'ASUS Vivobook 15',brand:'ASUS',category:'Laptops',price:42990,old:52990,rating:4.4,tag:'For students',image:'https://images.unsplash.com/photo-149 laptop?auto=format&fit=crop&w=900&q=85',spec:'Core i5 · 16GB RAM · 512GB SSD'},
 {id:3,name:'Sony WH-CH720N',brand:'Sony',category:'Audio',price:7990,old:9990,rating:4.6,tag:'Popular',image:'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=85',spec:'ANC · 35-hour battery'},
 {id:4,name:'Logitech G304',brand:'Logitech',category:'Gaming',price:2495,old:3995,rating:4.5,tag:'Gamer pick',image:'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=85',spec:'Wireless · 12,000 DPI'},
 {id:5,name:'Samsung 990 EVO SSD',brand:'Samsung',category:'PC Components',price:6999,old:8999,rating:4.7,tag:'Fast storage',image:'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=900&q=85',spec:'1TB · NVMe M.2'},
 {id:6,name:'Anker PowerCore 20K',brand:'Anker',category:'Accessories',price:3299,old:4499,rating:4.3,tag:'Travel essential',image:'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=900&q=85',spec:'20,000mAh ·  Power Delivery'}
];
const money=n=>'₹'+n.toLocaleString('en-IN');
function App(){
 const [active,setActive]=useState('All'); const [query,setQuery]=useState(''); const [mobileNav,setMobileNav]=useState(false); const [showLogin,setShowLogin]=useState(false); const [saved,setSaved]=useState([]);
 const filtered=useMemo(()=>products.filter(p=>(active==='All'||p.category===active)&&p.name.toLowerCase().includes(query.toLowerCase())),[active,query]);
 const toggleSave=id=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <div className="app">
  <div className="announcement">Tech that makes sense. Picks for every pocket. <span>Explore the latest deals <ArrowUpRight size={13}/></span></div>
  <header className="header">
   <a className="brand" href="#"><span className="brand-mark">TB</span><span>The Techy <b>Baba</b><small>YOUR TECH. YOUR BUDGET.</small></span></a>
   <nav className={mobileNav?'nav open':'nav'}>{['Home','Store','Compare','Buying Guides','Reviews','Tech News'].map((n,i)=><a className={i===0?'selected':''} href={i===1?'#store':'#'} key={n}>{n}{n==='Store'&&<ChevronDown size={14}/>}</a>)}</nav>
   <div className="header-actions"><button className="icon-btn" aria-label="Account" onClick={()=>setShowLogin(true)}><UserRound size={19}/><span>Sign in</span></button><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Menu">{mobileNav?<X/>:<Menu/>}</button></div>
  </header>
  <main>
   <section className="hero">
    <div className="hero-copy"><div className="eyebrow"><Zap size={14}/> THE SMARTER WAY TO SHOP TECH</div><h1>Good tech.<br/><em>Great decisions.</em></h1><p>Cut through the noise. Discover honest recommendations, compare specs, and find the right device for your budget.</p><div className="hero-buttons"><a className="btn primary" href="#store">Explore the store <ArrowUpRight size={16}/></a><a className="btn ghost" href="#categories">Browse categories</a></div><div className="hero-proof"><div className="avatars"><span>V</span><span>T</span><span>B</span></div><span><b>Made for curious minds</b><small>Clear advice. No tech jargon.</small></span></div></div>
    <div className="hero-visual"><div className="glow"></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1100&q=85" onError={e=>e.currentTarget.src='https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1100&q=85'} alt="Modern technology workspace"/></div><div className="floating-card"><span className="float-icon"><Star size={17} fill="currentColor"/></span><div><b>Choices, simplified.</b><small>Compare what matters.</small></div></div><div className="hero-index">01 <span>/</span> 04</div></div>
   </section>
   <section className="trust-strip"><div><ShieldCheck/><span><b>Research-led picks</b><small>Less guesswork, more confidence</small></span></div><div><SlidersHorizontal/><span><b>Compare with clarity</b><small>Specs that actually matter</small></span></div><div><Truck/><span><b>Shop from trusted stores</b><small>Amazon, Flipkart & more</small></span></div></section>
   <section className="section categories" id="categories"><div className="section-heading"><div><span className="eyebrow">EXPLORE BY INTEREST</span><h2>Find your <em>kind of tech.</em></h2></div><a href="#store" className="text-link">View all categories <ArrowUpRight size={15}/></a></div><div className="category-grid">{categories.map(({name,icon:Icon,sub})=><button className={'category-card '+(active===name?'active':'')} onClick={()=>{setActive(name);document.getElementById('store').scrollIntoView({behavior:'smooth'})}} key={name}><span className="category-icon"><Icon size={23}/></span><b>{name}</b><small>{sub}</small><ArrowUpRight className="cat-arrow" size={16}/></button>)}</div></section>
   <section className="section store" id="store"><div className="section-heading"><div><span className="eyebrow">THE TECHY BABA STORE</span><h2>Worth a closer <em>look.</em></h2><p className="section-desc">Handpicked gadgets with the details you need to decide.</p></div><div className="store-controls"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/></label><button className="filter-btn"><SlidersHorizontal size={16}/> Filters</button></div></div><div className="filter-pills"><button className={active==='All'?'pill active':'pill'} onClick={()=>setActive('All')}>All picks</button>{categories.map(c=><button className={active===c.name?'pill active':'pill'} onClick={()=>setActive(c.name)} key={c.name}>{c.name}</button>)}</div><div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-image"><img src={p.image} alt={p.name} onError={e=>e.currentTarget.src='https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=900&q=80'}/><span className="product-tag">{p.tag}</span><button className={'save-btn '+(saved.includes(p.id)?'saved':'')} onClick={()=>toggleSave(p.id)} aria-label="Save product"><Heart size={17} fill={saved.includes(p.id)?'currentColor':'none'}/></button></div><div className="product-info"><div className="product-brand">{p.brand} <span><Star size={13} fill="currentColor"/> {p.rating}</span></div><h3>{p.name}</h3><p>{p.spec}</p><div className="price-row"><div><b>{money(p.price)}</b><del>{money(p.old)}</del></div><span className="discount">{Math.round((1-p.price/p.old)*100)}% off</span></div><div className="buy-row"><button className="buy-btn" onClick={()=>alert('Add your Amazon affiliate URL for this product in the admin panel.')}>View deal <ArrowUpRight size={15}/></button><button className="compare-btn">Compare</button></div></div></article>)}</div>{filtered.length===0&&<div className="empty">No products found. Try another search or category.</div>}</section>
   <section className="budget-banner"><div><span className="eyebrow">SHOP SMARTER</span><h2>Big on value.<br/><em>Not on price.</em></h2><p>Explore buying guides curated around what you want to spend.</p><a className="btn light" href="#store">Find your budget pick <ArrowUpRight size={16}/></a></div><div className="budget-options">{['Under ₹5,000','Under ₹10,000','Under ₹20,000','Under ₹50,000'].map((x,i)=><button key={x} onClick={()=>{setActive('All');document.getElementById('store').scrollIntoView({behavior:'smooth'})}}><span>0{i+1}</span><b>{x}</b><ArrowUpRight size={17}/></button>)}</div></section>
   <section className="newsletter"><div><span className="eyebrow">THE TECHY BRIEF</span><h2>Good tech advice,<br/><em>straight to your inbox.</em></h2><p>New launches, useful comparisons and deals worth knowing about.</p></div><form onSubmit={e=>{e.preventDefault();alert('Thanks for subscribing!')}}><input type="email" placeholder="Your email address" required/><button className="btn primary">Subscribe <ArrowUpRight size={16}/></button><small>No spam. Just the good stuff.</small></form></section>
  </main>
  <footer><a className="brand" href="#"><span className="brand-mark">TB</span><span>The Techy <b>Baba</b><small>YOUR TECH. YOUR BUDGET.</small></span></a><p>Independent tech discovery, made simpler.</p><div className="footer-bottom"><span>© 2026 The Techy Baba</span><span>Affiliate disclosure · Privacy · Contact</span></div></footer>
  {showLogin&&<div className="modal-backdrop" onClick={()=>setShowLogin(false)}><div className="login-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowLogin(false)}><X/></button><span className="brand-mark">TB</span><h2>Welcome back.</h2><p>Sign in to save your picks and comparisons.</p><button className="btn primary full" onClick={()=>alert('Authentication will be connected in Phase 3.')}>Continue as user</button><button className="btn ghost full" onClick={()=>alert('Secure developer authentication will be connected in Phase 3.')}>Developer sign in</button><small>New here? Account creation arrives with authentication setup.</small></div></div>}
 </div>
}
export default App;